name: MacOS

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install depedencies using brew
      run: brew install pkgconfig libxml2 glibmm libxml++ jack liblo libsndfile gtkmm3 eigen boost gsl fftw libsamplerate cpprestsdk nlohmann-json openssl coreutils qt qtkeychain
    - name: Configure project
      run: mkdir build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: make
    - name: Create installer
      run: cpack
    - name: Publish installer
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/InstallDigitalStage.dmg
        tag: ${{ github.ref }}
        overwrite: true
      