name: MacOS

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: fetchtags
      run: git fetch --unshallow --tags
    - name: dependencies
      run: brew install pkgconfig libxml2 glibmm libxml++ jack liblo libsndfile gtkmm3 eigen boost gsl fftw libsamplerate cpprestsdk nlohmann-json openssl coreutils qt qtkeychain
    - name: Configure
      run: mkdir build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: Building
      run: make
    - name: Creating installer
      run: cpack
    - name: Publish installer
      uses: svenstaro/upload-release-action@v2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/InstallDigitalStage.dmg
        tag: ${{ github.ref }}
        overwrite: true
      